// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_S2cENwPtrb7fdUm7fh34yi2HBGELkY',
    appId: '1:44433425953:web:d7a74012c2d4e3ad164560',
    messagingSenderId: '44433425953',
    projectId: 'women-reach-9443c',
    authDomain: 'women-reach-9443c.firebaseapp.com',
    storageBucket: 'women-reach-9443c.appspot.com',
    measurementId: 'G-6HQF2T540L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFPmwjJ_GGtPev3PBuVKgMXsSf3_-i9p4',
    appId: '1:44433425953:android:f63391401c7506c9164560',
    messagingSenderId: '44433425953',
    projectId: 'women-reach-9443c',
    storageBucket: 'women-reach-9443c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBAV9IOXL3fh4EoxOGL67BSEDpTh49NA',
    appId: '1:44433425953:ios:928e3fcec4c7a5e1164560',
    messagingSenderId: '44433425953',
    projectId: 'women-reach-9443c',
    storageBucket: 'women-reach-9443c.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBAV9IOXL3fh4EoxOGL67BSEDpTh49NA',
    appId: '1:44433425953:ios:928e3fcec4c7a5e1164560',
    messagingSenderId: '44433425953',
    projectId: 'women-reach-9443c',
    storageBucket: 'women-reach-9443c.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_S2cENwPtrb7fdUm7fh34yi2HBGELkY',
    appId: '1:44433425953:web:d4e7300c98b722b6164560',
    messagingSenderId: '44433425953',
    projectId: 'women-reach-9443c',
    authDomain: 'women-reach-9443c.firebaseapp.com',
    storageBucket: 'women-reach-9443c.appspot.com',
    measurementId: 'G-BKW98RVV2X',
  );
}
